### PR TITLE
fix(adm): Use Firefox's full_keyword algorithm

### LINKED ISSUE #213: Merino Sponsored/Non-Sponsored results have extra keywords suggested
See also on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1740476).

Compared to RemoteSettings counterparts, Firefox showed extra keywords in the title of the Merino suggestions.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/CONSVC-1357)
┆Epic: merino-nightly-test

### PR DESCRIPTION
**Pull request by mythmon**
Notably, this algorithm never suggests more than the rest of the current word.

Fixes #213

### CODE REVIEW

File: merino-adm/src/remote_settings/mod.rs [hunk 1]
```diff
@@ -157,28 +157,33 @@ impl RemoteSettingsSuggester {
...
                         .contains(&adm_suggestion.iab_category.as_str()),
                     icon: icon_url,
                     score: Proportion::from(0.2),
                 };
+
                 for keyword in &adm_suggestion.keywords {
-                    new_suggestions.insert(keyword.clone(), merino_suggestion.clone());
+                    let full_keyword = Self::get_full_keyword(keyword, &adm_suggestion.keywords);
+
+                    if keyword == "amaz" {
```
Comment (ncloudioj) [inline merino-adm/src/remote_settings/mod.rs:177]: Debugging leftover?

File: merino-adm/src/remote_settings/mod.rs [hunk 2]
```diff
@@ -202,6 +207,41 @@ impl RemoteSettingsSuggester {
 
         Ok(())
     }
+
+    /// Gets the "full keyword" (the suggested completion) for a query. The data
+    /// from adM doesn't include this data directly, so we make our own based on
+    /// the available keywords.
+    ///
+    /// 1. Find the first keyword phrase that has more words than the query. Use
+    ///    its first `queryWords.length` words as the full keyword. e.g., if the
```
Comment (ncloudioj) [inline merino-adm/src/remote_settings/mod.rs:216]: Could you update the doc to reflect the variables used in the function? `queryWords` and `result.keywords` are a little confusing here.

**Review by ncloudioj — APPROVED** [review]
r+ w/ comments.
